name: Build

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:
  repository_dispatch:
    types: [ build ]

jobs:
  build:
    name: build
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        node: [ 18.14.0 ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: |
          npm ci
          npm run build
